### ISSUE TITLE
ProteinPaint web

### ISSUE THREAD

**Issue by twelvesummer** [JhuangLab/ngstk#1]
Hello,I wanna use ProteinPaint application in web,but I didn't find the submittor.Is this application closing?

**Comment by Miachol** [comment]
You can try this URL: https://proteinpaint.stjude.org/.

**Comment by twelvesummer** [comment]
thank you.This web need to VPN in China.

**Comment by Miachol** [comment]
You can try http://bioinfo.rjh.com.cn/proteinpaint/ in China. Our lab has migrated partial function.
